### ISSUE TITLE
non docker deployment

### ISSUE THREAD

**Issue by thindata** [nning/imgshr#1161]
Is it possible/is there a how to on deploying this to a shared hosting environment that does not have docker?

**Comment by nning** [comment]
It could be possible if the shared hosting environment supports Ruby on Rails. There is no documentation on this, yet, as it would be very dependent on the hosting provider.
The basic "deployment model" is the same as with other Rails apps or any web app that's deployed as a separate process (to the webserver). Basically, you need MySQL, Redis and a webserver with a reverse proxy configuration pointing to the Rails process.
