### ISSUE TITLE
Client side encryption key sharing by URL

### ISSUE THREAD

**Issue by ingobecker** [nning/imgshr#39]
Sharing keys for client side encryption is done by attaching them to the hash part of a gallery URL. This solves the problem of including the key into URL and preventing the browser from sending it to the server while visiting it. 

Following problems arise by doing so:

1. The hash part is saved in the global browser history and it seems that there is nothing that could be done about it from a programmers point of view.

2. It is very easy to leak the key for example by pasting it online, using link shorteners etc.

One way to deal with it, might be to display a warning that points out those problems, if a user tries to share the key by URL. 

Possible paths to a URL with a key in it should be minimized.

In case a user visits a URL with a key in it, the hash must be removed from the URL by js immediately to minimize the risk of the user to paste a leaky url.
Also a flash msg should be shown which says something like "please clean your history" every time a URL is visited that contains a key.

Another solution could be to only "allow" key sharing by URL via a qrcode. Simply remove all ways from the site that gives the user access to a URL with a key in it. This prevents the user from pasting it to the wrong location.

The qrcode should only be shown if the user explicitly demands for it and it should be the only qrcode that is shown in this case. It is very easy to confuse the qrcode with- and without the key.

**Comment by nning** [comment]
Hash part of URL is removed now after being set as key. It is no longer present in browser history. QR code is still also a link, because sharing by copy and pasting an ordinary link is necessary for devices without a QR code scanner.

Also either the QR code for the regular gallery URL or with client encryption key is shown, now.

**Comment by ingobecker** [comment]
According to this [documentation](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method) `history.replaceState()` doesn't have an impact on the global browser history. It removes the link from the history stack of the _user session_ . Visiting links creates history entries which can't be avoided. Cleaning the history manually is mandatory to get rid of leaky history entries.

**Comment by ingobecker** [comment]
Something that avoids a history entry would be the possibility to visit the link of a gallery and paste the key from the clipboard into a form field, which sets the key.

**Comment by nning** [comment]
I just checked whether the URL containing the key gets suggested in the address bar of a new tab in Firefox and it seemed the solution suffixes.

I reopen this issue for adding that flash message. Is having the key saved in localStorage different than having it saved in the browser history in your opinion?

**Comment by nning** [comment]
I thought about the possibility to specify the key by input but think it can not be the only way, because that impairs sharing.

**Comment by ingobecker** [comment]
The difference between having the key in URLs which get stored in the history over having it in localStorage is that one can easily confuse the URL of a gallery with the key appended with the one that doesn't. Same reason why in my opinion it makes sense to remove the key from the URL by js once it's stored in localStorage.
I agree, sharing a key that involves the users intervention is not as easy as scaning a qrcode. But on the other hand, it saves the user from cunfusing the URL with and without the secret key. I think it might be ok to show a warning, instructing the user to clear the history manually, but as we know, users tend to just click ok instead of carefully reading it, every time a warning gets into the users way.
