### ISSUE TITLE
Wrong, random(?) key shown if visiting encrypted gallery without a key

### ISSUE THREAD

**Issue by ingobecker** [nning/imgshr#40]
If an encrypted gallery is visited without the right key, a random key is shown as well as a qrcode to share it which doesn't belong to the gallery. In this case all encryption informations should be omited instead.

**Comment by nning** [comment]
Key is replaced now if specified as hash in URL.

**Comment by ingobecker** [comment]
It still shows a random key. If you point your browser to a gallery without a key in the URL nor the localStorage it shows a qrcode with a key and a random key in the field below. The only thing that is omitted is the general sharing link of the gallery.

**Comment by nning** [comment]
Key is only replaced if new one gets passed by hash. It is more easy to keep generating a key if no one is stored or passed, because that is what is relied upon after gallery gets configured to be client encrypted.
